### ISSUE TITLE
「02速度計画」のplotjugglerインストールコマンドに関して

### ISSUE THREAD

**Issue by KariControl** [AutomotiveAIChallenge/aichallenge-documentation#33]
-懸念点
Autoware入門講座における「02速度計画」記載のコマンドだと、plotjugglerをインストールできない。
コマンド：「sudo apt install ros-humble plotjuggler-ros」

-提案
「humble」と「plotjugller-ros」の間にハイフンが抜けていることが原因と考えられる。下記コマンドであれば、インストール可能なことを確認済み。軽微なタイポと考えられるため、他のissueにおける修正のついでに変更いただくとよいと思います。

コマンド：sudo apt install ros-humble-plotjuggler-ros

**Comment by masahiro-kubota** [comment]
@KariControl 
イシューありがとうございます！
返信遅れてしまい申し訳ありません。
こちらのイシューは[ajinori3](https://github.com/AutomotiveAIChallenge/aichallenge-documentation-2024/pull/25)様が修正してくださいましたのでクローズさせていただきます！
また、今後のドキュメントの作成は[aichallenge-documentation-2024](https://github.com/AutomotiveAIChallenge/aichallenge-documentation-2024)の方でしていき、この[aichallenge-documentation](https://github.com/AutomotiveAIChallenge/)は大会終了後に講座等をsyncさせる方針となりました。

もし、前回PR頂いたシェルスクリプトに関するドキュメントの修正がありましたら[aichallenge-documentation-2024](https://github.com/AutomotiveAIChallenge/aichallenge-documentation-2024)の方にPR頂けると大変ありがたいです。

よろしくお願いいたします！
